# Generated by Django 5.2.7 on 2025-11-03 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomArtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('art_type', models.CharField(choices=[('oil', 'Oil Painting'), ('water', 'Watercolor Painting'), ('acrylic', 'Acrylic Painting'), ('digital', 'Digital Art'), ('charcoal', 'Charcoal Drawing'), ('pencil', 'Pencil Sketch'), ('sculpture', 'Sculpture'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('length', models.CharField(help_text='e.g., 24x36 inches', max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist_request', models.TextField(blank=True, help_text='Any specific artist preference', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
