# Generated by Django 5.2.7 on 2026-01-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Mark if this is AI-generated'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='prompt',
            field=models.TextField(blank=True, help_text='The prompt used to generate this image'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='source_model',
            field=models.CharField(blank=True, default='Stable Diffusion API', help_text='Which AI model generated this', max_length=100),
        ),
    ]
