# Generated by Django 5.2.7 on 2026-01-11 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artwork_is_ai_generated_artwork_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='source_model',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(choices=[('auction', 'Live Auction'), ('normal', 'Normal Sale')], default='normal', max_length=10),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='artworks.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
